name: Cargo Release PR
description: Create a PR for a release of a Rust/Cargo crate, using cargo-release
branding:
  icon: package
  color: orange
inputs:
  github-token:
    description: GitHub token to interact with the API
    required: true
  crate-name:
    description: Crate to release, if the repo has more than one
    required: false
  crate-path:
    description: Path to the crate; defaults to resolving it from workspace
    required: false
  crate-release-all:
    description: Release all crates in the workspace
    required: true
    default: false
  version:
    description: Version to release, or one of the keywords `major`, `minor`, `patch`
    required: true
  pr-title:
    description: Literal or template for the title of the PR
    required: true
    default: "release: <%= crate.name %> v<%= version.actual %>"
  pr-label:
    description: Label name to apply to created PR
    required: false
  pr-draft:
    description: Create the release PR as Draft
    required: true
    default: false
  pr-modifiable:
    description: Allow maintainers to modify the release PR
    required: true
    default: true
  pr-template:
    description: Template for the body of the PR (mutually exclusive with `pr-template-file`)
    required: false
  pr-template-file:
    description: Template file for the body of the PR (mutually exclusive with `pr-template`)
    required: false
  pr-merge-strategy:
    description: Merge strategy that should be used (`squash`, `merge`, `rebase`, `bors`)
    required: true
    default: squash
  pr-release-notes:
    description: Include a release notes section in the PR body
    required: true
    default: false
  git-user-name:
    description: Name of the git user that will commit the release
    required: true
    default: github-actions
  git-user-email:
    description: Email of the git user that will commit the release
    required: true
    default: github-actions@github.com
  check-semver:
    description: Run cargo-semver-checks before committing to the release
    required: true
    default: false
  base-branch:
    description: Name of the PR's base branch (where it will merge). Defaults to repo's default branch.
    required: false
  branch-prefix:
    description: Prefix of the release branch created for the PR
    required: true
    default: release
outputs:
  pr-branch:
    description: Branch name of the release PR
  pr-url:
    description: URL to the release PR
  version:
    description: The version created for the PR
runs:
  using: node16
  main: dist/index.js
